<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\CategoryAttributes;
use App\Models\ProductAttribute;
use Faker\Generator;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;

class CategorySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $faker = app(Generator::class);
        $productAttributes = ProductAttribute::all();

        $categoryAttributes = [
            'Clothing' => ['Condition', 'Color', 'Size'],
            'Electronics' => ['Color', 'Condition'],
            'Appliances' => ['Color', 'Condition'],
            'Men' => ['Condition', 'Color', 'Size'],
            'Women' => ['Condition', 'Color', 'Size'],
            'Kids' => ['Condition', 'Color', 'Size'],
            'Entertainment' => ['Color', 'Size', 'Condition'],
            'Board Games' => ['Color', 'Size', 'Condition'],
            'Puzzles' => ['Color', 'Size', 'Condition'],
            'Books' => ['Color', 'Size', 'Condition'],
            'Music' => ['Color', 'Condition'],
            'Video' => ['Color', 'Condition'],
            'Gaming' => ['Color', 'Condition']
        ];

        $categories = [
            [
                'parent_id' => 0,
                'name' => 'Clothing',
                'slug' => 'clothing',
                'image' => Str::replace('categories/', '', collect(Storage::disk('public')->files('categories'))->random()),
                'is_featured' => 1,
                'menu_status' => 1,
                'active' => 1,
                'description' => $faker->sentence(),
                'meta_title' => $faker->sentence(),
                'meta_keywords' => $faker->word(),
            ],
            [
                'parent_id' => 0,
                'name' => 'Entertainment',
                'slug' => 'entertainment',
                'image' => Str::replace('categories/', '', collect(Storage::disk('public')->files('categories'))->random()),
                'is_featured' => 1,
                'menu_status' => 1,
                'active' => 1,
                'description' => $faker->sentence(),
                'meta_title' => $faker->sentence(),
                'meta_keywords' => $faker->word(),
            ],
            [
                'parent_id' => 0,
                'name' => 'Electronics',
                'slug' => 'electronics',
                'image' => Str::replace('categories/', '', collect(Storage::disk('public')->files('categories'))->random()),
                'is_featured' => 1,
                'menu_status' => 1,
                'active' => 1,
                'description' => $faker->sentence(),
                'meta_title' => $faker->sentence(),
                'meta_keywords' => $faker->word(),
            ],
            [
                'parent_id' => 1,
                'name' => 'Men',
                'slug' => 'men',
                'image' => Str::replace('categories/', '', collect(Storage::disk('public')->files('categories'))->random()),
                'is_featured' => 1,
                'menu_status' => 1,
                'active' => 1,
                'description' => $faker->sentence(),
                'meta_title' => $faker->sentence(),
                'meta_keywords' => $faker->word(),
            ],
            [
                'parent_id' => 1,
                'name' => 'Women',
                'slug' => 'women',
                'image' => Str::replace('categories/', '', collect(Storage::disk('public')->files('categories'))->random()),
                'is_featured' => 1,
                'menu_status' => 1,
                'active' => 1,
                'description' => $faker->sentence(),
                'meta_title' => $faker->sentence(),
                'meta_keywords' => $faker->word(),
            ],
            [
                'parent_id' => 1,
                'name' => 'Kids',
                'slug' => 'kids',
                'image' => Str::replace('categories/', '', collect(Storage::disk('public')->files('categories'))->random()),
                'is_featured' => 1,
                'menu_status' => 1,
                'active' => 1,
                'description' => $faker->sentence(),
                'meta_title' => $faker->sentence(),
                'meta_keywords' => $faker->word(),
            ],
            [
                'parent_id' => 2,
                'name' => 'Board Games',
                'slug' => 'board-games',
                'image' => Str::replace('categories/', '', collect(Storage::disk('public')->files('categories'))->random()),
                'is_featured' => 1,
                'menu_status' => 1,
                'active' => 1,
                'description' => $faker->sentence(),
                'meta_title' => $faker->sentence(),
                'meta_keywords' => $faker->word(),
            ],
            [
                'parent_id' => 2,
                'name' => 'Books',
                'slug' => 'books',
                'image' => Str::replace('categories/', '', collect(Storage::disk('public')->files('categories'))->random()),
                'is_featured' => 1,
                'menu_status' => 1,
                'active' => 1,
                'description' => $faker->sentence(),
                'meta_title' => $faker->sentence(),
                'meta_keywords' => $faker->word(),
            ],
            [
                'parent_id' => 2,
                'name' => 'Music',
                'slug' => 'music',
                'image' => Str::replace('categories/', '', collect(Storage::disk('public')->files('categories'))->random()),
                'is_featured' => 1,
                'menu_status' => 1,
                'active' => 1,
                'description' => $faker->sentence(),
                'meta_title' => $faker->sentence(),
                'meta_keywords' => $faker->word(),
            ],
            [
                'parent_id' => 2,
                'name' => 'Puzzles',
                'slug' => 'puzzles',
                'image' => Str::replace('categories/', '', collect(Storage::disk('public')->files('categories'))->random()),
                'is_featured' => 1,
                'menu_status' => 1,
                'active' => 1,
                'description' => $faker->sentence(),
                'meta_title' => $faker->sentence(),
                'meta_keywords' => $faker->word(),
            ],
            [
                'parent_id' => 2,
                'name' => 'Video',
                'slug' => 'video',
                'image' => Str::replace('categories/', '', collect(Storage::disk('public')->files('categories'))->random()),
                'is_featured' => 1,
                'menu_status' => 1,
                'active' => 1,
                'description' => $faker->sentence(),
                'meta_title' => $faker->sentence(),
                'meta_keywords' => $faker->word(),
            ],
            [
                'parent_id' => 2,
                'name' => 'Gaming',
                'slug' => 'gaming',
                'image' => Str::replace('categories/', '', collect(Storage::disk('public')->files('categories'))->random()),
                'is_featured' => 1,
                'menu_status' => 1,
                'active' => 1,
                'description' => $faker->sentence(),
                'meta_title' => $faker->sentence(),
                'meta_keywords' => $faker->word(),
            ],
            [
                'parent_id' => 3,
                'name' => 'Video Games & Consoles',
                'slug' => 'video-games',
                'image' => Str::replace('categories/', '', collect(Storage::disk('public')->files('categories'))->random()),
                'is_featured' => 1,
                'menu_status' => 1,
                'active' => 1,
                'description' => $faker->sentence(),
                'meta_title' => $faker->sentence(),
                'meta_keywords' => $faker->word(),
            ],
            [
                'parent_id' => 3,
                'name' => 'Computers & Accessories',
                'slug' => 'computers',
                'image' => Str::replace('categories/', '', collect(Storage::disk('public')->files('categories'))->random()),
                'is_featured' => 1,
                'menu_status' => 1,
                'active' => 1,
                'description' => $faker->sentence(),
                'meta_title' => $faker->sentence(),
                'meta_keywords' => $faker->word(),
            ],
            [
                'parent_id' => 3,
                'name' => 'Mobiles & Accessories',
                'slug' => 'mobiles',
                'image' => Str::replace('categories/', '', collect(Storage::disk('public')->files('categories'))->random()),
                'is_featured' => 1,
                'menu_status' => 1,
                'active' => 1,
                'description' => $faker->sentence(),
                'meta_title' => $faker->sentence(),
                'meta_keywords' => $faker->word(),
            ],
            [
                'parent_id' => 3,
                'name' => 'Headphones',
                'slug' => 'headphones',
                'image' => Str::replace('categories/', '', collect(Storage::disk('public')->files('categories'))->random()),
                'is_featured' => 1,
                'menu_status' => 1,
                'active' => 1,
                'description' => $faker->sentence(),
                'meta_title' => $faker->sentence(),
                'meta_keywords' => $faker->word(),
            ],
            [
                'parent_id' => 3,
                'name' => 'Cameras & Photography',
                'slug' => 'cameras',
                'image' => Str::replace('categories/', '', collect(Storage::disk('public')->files('categories'))->random()),
                'is_featured' => 1,
                'menu_status' => 1,
                'active' => 1,
                'description' => $faker->sentence(),
                'meta_title' => $faker->sentence(),
                'meta_keywords' => $faker->word(),
            ],
            [
                'parent_id' => 3,
                'name' => 'Tv\'s',
                'slug' => 'tv',
                'image' => Str::replace('categories/', '', collect(Storage::disk('public')->files('categories'))->random()),
                'is_featured' => 1,
                'menu_status' => 1,
                'active' => 1,
                'description' => $faker->sentence(),
                'meta_title' => $faker->sentence(),
                'meta_keywords' => $faker->word(),
            ],
            [
                'parent_id' => 0,
                'name' => 'Home and Garden',
                'slug' => 'home-and-garden',
                'image' => Str::replace('categories/', '', collect(Storage::disk('public')->files('categories'))->random()),
                'is_featured' => 1,
                'menu_status' => 1,
                'active' => 1,
                'description' => $faker->sentence(),
                'meta_title' => $faker->sentence(),
                'meta_keywords' => $faker->word(),
            ],
            [
                'parent_id' => 19,
                'name' => 'Garden',
                'slug' => 'garden',
                'image' => Str::replace('categories/', '', collect(Storage::disk('public')->files('categories'))->random()),
                'is_featured' => 1,
                'menu_status' => 1,
                'active' => 1,
                'description' => $faker->sentence(),
                'meta_title' => $faker->sentence(),
                'meta_keywords' => $faker->word(),
            ],
            [
                'parent_id' => 20,
                'name' => 'Power Tools',
                'slug' => 'power-tools',
                'image' => Str::replace('categories/', '', collect(Storage::disk('public')->files('categories'))->random()),
                'is_featured' => 1,
                'menu_status' => 1,
                'active' => 1,
                'description' => $faker->sentence(),
                'meta_title' => $faker->sentence(),
                'meta_keywords' => $faker->word(),
            ],
            [
                'parent_id' => 20,
                'name' => 'Outdoor Lighting',
                'slug' => 'outdoor-lighting',
                'image' => Str::replace('categories/', '', collect(Storage::disk('public')->files('categories'))->random()),
                'is_featured' => 1,
                'menu_status' => 1,
                'active' => 1,
                'description' => $faker->sentence(),
                'meta_title' => $faker->sentence(),
                'meta_keywords' => $faker->word(),
            ],
            [
                'parent_id' => 20,
                'name' => 'Plants',
                'slug' => 'plants',
                'image' => Str::replace('categories/', '', collect(Storage::disk('public')->files('categories'))->random()),
                'is_featured' => 1,
                'menu_status' => 1,
                'active' => 1,
                'description' => $faker->sentence(),
                'meta_title' => $faker->sentence(),
                'meta_keywords' => $faker->word(),
            ],
            [
                'parent_id' => 20,
                'name' => 'Patio Furniture',
                'slug' => 'patio',
                'image' => Str::replace('categories/', '', collect(Storage::disk('public')->files('categories'))->random()),
                'is_featured' => 1,
                'menu_status' => 1,
                'active' => 1,
                'description' => $faker->sentence(),
                'meta_title' => $faker->sentence(),
                'meta_keywords' => $faker->word(),
            ],
            [
                'parent_id' => 19,
                'name' => 'Kitchen Appliances',
                'slug' => 'kitchen',
                'image' => Str::replace('categories/', '', collect(Storage::disk('public')->files('categories'))->random()),
                'is_featured' => 1,
                'menu_status' => 1,
                'active' => 1,
                'description' => $faker->sentence(),
                'meta_title' => $faker->sentence(),
                'meta_keywords' => $faker->word(),
            ],
            [
                'parent_id' => 25,
                'name' => 'Fridges',
                'slug' => 'fridges',
                'image' => Str::replace('categories/', '', collect(Storage::disk('public')->files('categories'))->random()),
                'is_featured' => 1,
                'menu_status' => 1,
                'active' => 1,
                'description' => $faker->sentence(),
                'meta_title' => $faker->sentence(),
                'meta_keywords' => $faker->word(),
            ],
            [
                'parent_id' => 25,
                'name' => 'Dishwashers',
                'slug' => 'dishwashers',
                'image' => Str::replace('categories/', '', collect(Storage::disk('public')->files('categories'))->random()),
                'is_featured' => 1,
                'menu_status' => 1,
                'active' => 1,
                'description' => $faker->sentence(),
                'meta_title' => $faker->sentence(),
                'meta_keywords' => $faker->word(),
            ],
            [
                'parent_id' => 19,
                'name' => 'Cooking Appliances',
                'slug' => 'cooking-appliances',
                'image' => Str::replace('categories/', '', collect(Storage::disk('public')->files('categories'))->random()),
                'is_featured' => 1,
                'menu_status' => 1,
                'active' => 1,
                'description' => $faker->sentence(),
                'meta_title' => $faker->sentence(),
                'meta_keywords' => $faker->word(),
            ],
            [
                'parent_id' => 19,
                'name' => 'Cooking',
                'slug' => 'cooking',
                'image' => Str::replace('categories/', '', collect(Storage::disk('public')->files('categories'))->random()),
                'is_featured' => 1,
                'menu_status' => 1,
                'active' => 1,
                'description' => $faker->sentence(),
                'meta_title' => $faker->sentence(),
                'meta_keywords' => $faker->word(),
            ],
            [
                'parent_id' => 29,
                'name' => 'Drinkware',
                'slug' => 'drinkware',
                'image' => Str::replace('categories/', '', collect(Storage::disk('public')->files('categories'))->random()),
                'is_featured' => 1,
                'menu_status' => 1,
                'active' => 1,
                'description' => $faker->sentence(),
                'meta_title' => $faker->sentence(),
                'meta_keywords' => $faker->word(),
            ],
            [
                'parent_id' => 29,
                'name' => 'Cookware',
                'slug' => 'cookware',
                'image' => Str::replace('categories/', '', collect(Storage::disk('public')->files('categories'))->random()),
                'is_featured' => 1,
                'menu_status' => 1,
                'active' => 1,
                'description' => $faker->sentence(),
                'meta_title' => $faker->sentence(),
                'meta_keywords' => $faker->word(),
            ],
            [
                'parent_id' => 29,
                'name' => 'Utensils',
                'slug' => 'utensils',
                'image' => Str::replace('categories/', '', collect(Storage::disk('public')->files('categories'))->random()),
                'is_featured' => 1,
                'menu_status' => 1,
                'active' => 1,
                'description' => $faker->sentence(),
                'meta_title' => $faker->sentence(),
                'meta_keywords' => $faker->word(),
            ],
            [
                'parent_id' => 25,
                'name' => 'Washing Machines',
                'slug' => 'washing-machines',
                'image' => Str::replace('categories/', '', collect(Storage::disk('public')->files('categories'))->random()),
                'is_featured' => 1,
                'menu_status' => 1,
                'active' => 1,
                'description' => $faker->sentence(),
                'meta_title' => $faker->sentence(),
                'meta_keywords' => $faker->word(),
            ],
            [
                'parent_id' => 25,
                'name' => 'Tumble Dryers',
                'slug' => 'tumble-dryers',
                'image' => Str::replace('categories/', '', collect(Storage::disk('public')->files('categories'))->random()),
                'is_featured' => 1,
                'menu_status' => 1,
                'active' => 1,
                'description' => $faker->sentence(),
                'meta_title' => $faker->sentence(),
                'meta_keywords' => $faker->word(),
            ],
            [
                'parent_id' => 25,
                'name' => 'Ovens',
                'slug' => 'ovens',
                'image' => Str::replace('categories/', '', collect(Storage::disk('public')->files('categories'))->random()),
                'is_featured' => 1,
                'menu_status' => 1,
                'active' => 1,
                'description' => $faker->sentence(),
                'meta_title' => $faker->sentence(),
                'meta_keywords' => $faker->word(),
            ],
            [
                'parent_id' => 28,
                'name' => 'Fryers',
                'slug' => 'fryers',
                'image' => Str::replace('categories/', '', collect(Storage::disk('public')->files('categories'))->random()),
                'is_featured' => 1,
                'menu_status' => 1,
                'active' => 1,
                'description' => $faker->sentence(),
                'meta_title' => $faker->sentence(),
                'meta_keywords' => $faker->word(),
            ],
            [
                'parent_id' => 28,
                'name' => 'Kettles',
                'slug' => 'kettles',
                'image' => Str::replace('categories/', '', collect(Storage::disk('public')->files('categories'))->random()),
                'is_featured' => 1,
                'menu_status' => 1,
                'active' => 1,
                'description' => $faker->sentence(),
                'meta_title' => $faker->sentence(),
                'meta_keywords' => $faker->word(),
            ],
            [
                'parent_id' => 28,
                'name' => 'Toasters',
                'slug' => 'toasters',
                'image' => Str::replace('categories/', '', collect(Storage::disk('public')->files('categories'))->random()),
                'is_featured' => 1,
                'menu_status' => 1,
                'active' => 1,
                'description' => $faker->sentence(),
                'meta_title' => $faker->sentence(),
                'meta_keywords' => $faker->word(),
            ],
        ];

        $allCategories = Category::all()->keyBy('name');

        foreach ($categories as $category) {
            if ($allCategories->has(($category['name']))) {
                continue;
            }

            $category = Category::create($category);

            if (array_key_exists($category['name'], $categoryAttributes)) {
                foreach ($categoryAttributes[$category['name']] as $key => $value) {
                    $attribute = $productAttributes->where('name', $value)->first()->id;

                    CategoryAttributes::create([
                        'category_id' => $category->id,
                        'attribute_id' => $attribute,
                        'active' => true,
                    ]);
                }
            }
        }
    }
}
