<?php

declare(strict_types=1);

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run()
    {
        DB::table('countries')->delete();

        $countries = [
            ['code' => 'US', 'name' => 'United States', 'shipping_active' => true],
            ['code' => 'CA', 'name' => 'Canada', 'shipping_active' => true],
            ['code' => 'AF', 'name' => 'Afghanistan', 'shipping_active' => false],
            ['code' => 'AL', 'name' => 'Albania', 'shipping_active' => false],
            ['code' => 'DZ', 'name' => 'Algeria', 'shipping_active' => false],
            ['code' => 'AS', 'name' => 'American Samoa', 'shipping_active' => false],
            ['code' => 'AD', 'name' => 'Andorra', 'shipping_active' => false],
            ['code' => 'AO', 'name' => 'Angola', 'shipping_active' => false],
            ['code' => 'AI', 'name' => 'Anguilla', 'shipping_active' => false],
            ['code' => 'AQ', 'name' => 'Antarctica', 'shipping_active' => false],
            ['code' => 'AG', 'name' => 'Antigua and/or Barbuda', 'shipping_active' => false],
            ['code' => 'AR', 'name' => 'Argentina', 'shipping_active' => false],
            ['code' => 'AM', 'name' => 'Armenia', 'shipping_active' => false],
            ['code' => 'AW', 'name' => 'Aruba', 'shipping_active' => false],
            ['code' => 'AU', 'name' => 'Australia', 'shipping_active' => false],
            ['code' => 'AT', 'name' => 'Austria', 'shipping_active' => false],
            ['code' => 'AZ', 'name' => 'Azerbaijan', 'shipping_active' => false],
            ['code' => 'BS', 'name' => 'Bahamas', 'shipping_active' => false],
            ['code' => 'BH', 'name' => 'Bahrain', 'shipping_active' => false],
            ['code' => 'BD', 'name' => 'Bangladesh', 'shipping_active' => false],
            ['code' => 'BB', 'name' => 'Barbados', 'shipping_active' => false],
            ['code' => 'BY', 'name' => 'Belarus', 'shipping_active' => false],
            ['code' => 'BE', 'name' => 'Belgium', 'shipping_active' => false],
            ['code' => 'BZ', 'name' => 'Belize', 'shipping_active' => false],
            ['code' => 'BJ', 'name' => 'Benin', 'shipping_active' => false],
            ['code' => 'BM', 'name' => 'Bermuda', 'shipping_active' => false],
            ['code' => 'BT', 'name' => 'Bhutan', 'shipping_active' => false],
            ['code' => 'BO', 'name' => 'Bolivia', 'shipping_active' => false],
            ['code' => 'BA', 'name' => 'Bosnia and Herzegovina', 'shipping_active' => false],
            ['code' => 'BW', 'name' => 'Botswana', 'shipping_active' => false],
            ['code' => 'BV', 'name' => 'Bouvet Island', 'shipping_active' => false],
            ['code' => 'BR', 'name' => 'Brazil', 'shipping_active' => false],
            ['code' => 'IO', 'name' => 'British lndian Ocean Territory', 'shipping_active' => false],
            ['code' => 'BN', 'name' => 'Brunei Darussalam', 'shipping_active' => false],
            ['code' => 'BG', 'name' => 'Bulgaria', 'shipping_active' => false],
            ['code' => 'BF', 'name' => 'Burkina Faso', 'shipping_active' => false],
            ['code' => 'BI', 'name' => 'Burundi', 'shipping_active' => false],
            ['code' => 'KH', 'name' => 'Cambodia', 'shipping_active' => false],
            ['code' => 'CM', 'name' => 'Cameroon', 'shipping_active' => false],
            ['code' => 'CV', 'name' => 'Cape Verde', 'shipping_active' => false],
            ['code' => 'KY', 'name' => 'Cayman Islands', 'shipping_active' => false],
            ['code' => 'CF', 'name' => 'Central African Republic', 'shipping_active' => false],
            ['code' => 'TD', 'name' => 'Chad', 'shipping_active' => false],
            ['code' => 'CL', 'name' => 'Chile', 'shipping_active' => true],
            ['code' => 'CN', 'name' => 'China', 'shipping_active' => true],
            ['code' => 'CX', 'name' => 'Christmas Island', 'shipping_active' => false],
            ['code' => 'CC', 'name' => 'Cocos (Keeling) Islands', 'shipping_active' => false],
            ['code' => 'CO', 'name' => 'Colombia', 'shipping_active' => true],
            ['code' => 'KM', 'name' => 'Comoros', 'shipping_active' => false],
            ['code' => 'CG', 'name' => 'Congo', 'shipping_active' => false],
            ['code' => 'CK', 'name' => 'Cook Islands', 'shipping_active' => false],
            ['code' => 'CR', 'name' => 'Costa Rica', 'shipping_active' => false],
            ['code' => 'HR', 'name' => 'Croatia (Hrvatska)', 'shipping_active' => false],
            ['code' => 'CU', 'name' => 'Cuba', 'shipping_active' => false],
            ['code' => 'CY', 'name' => 'Cyprus', 'shipping_active' => true],
            ['code' => 'CZ', 'name' => 'Czech Republic', 'shipping_active' => false],
            ['code' => 'CD', 'name' => 'Democratic Republic of Congo', 'shipping_active' => false],
            ['code' => 'DK', 'name' => 'Denmark', 'shipping_active' => false],
            ['code' => 'DJ', 'name' => 'Djibouti', 'shipping_active' => false],
            ['code' => 'DM', 'name' => 'Dominica', 'shipping_active' => false],
            ['code' => 'DO', 'name' => 'Dominican Republic', 'shipping_active' => false],
            ['code' => 'TP', 'name' => 'East Timor', 'shipping_active' => false],
            ['code' => 'EC', 'name' => 'Ecudaor', 'shipping_active' => false],
            ['code' => 'EG', 'name' => 'Egypt', 'shipping_active' => false],
            ['code' => 'SV', 'name' => 'El Salvador', 'shipping_active' => false],
            ['code' => 'GQ', 'name' => 'Equatorial Guinea', 'shipping_active' => false],
            ['code' => 'ER', 'name' => 'Eritrea', 'shipping_active' => false],
            ['code' => 'EE', 'name' => 'Estonia', 'shipping_active' => false],
            ['code' => 'ET', 'name' => 'Ethiopia', 'shipping_active' => false],
            ['code' => 'FK', 'name' => 'Falkland Islands (Malvinas)', 'shipping_active' => false],
            ['code' => 'FO', 'name' => 'Faroe Islands', 'shipping_active' => false],
            ['code' => 'FJ', 'name' => 'Fiji', 'shipping_active' => false],
            ['code' => 'FI', 'name' => 'Finland', 'shipping_active' => false],
            ['code' => 'FR', 'name' => 'France', 'shipping_active' => false],
            ['code' => 'FX', 'name' => 'France, Metropolitan', 'shipping_active' => false],
            ['code' => 'GF', 'name' => 'French Guiana', 'shipping_active' => false],
            ['code' => 'PF', 'name' => 'French Polynesia', 'shipping_active' => false],
            ['code' => 'TF', 'name' => 'French Southern Territories', 'shipping_active' => false],
            ['code' => 'GA', 'name' => 'Gabon', 'shipping_active' => false],
            ['code' => 'GM', 'name' => 'Gambia', 'shipping_active' => false],
            ['code' => 'GE', 'name' => 'Georgia', 'shipping_active' => false],
            ['code' => 'DE', 'name' => 'Germany', 'shipping_active' => false],
            ['code' => 'GH', 'name' => 'Ghana', 'shipping_active' => false],
            ['code' => 'GI', 'name' => 'Gibraltar', 'shipping_active' => false],
            ['code' => 'GR', 'name' => 'Greece', 'shipping_active' => false],
            ['code' => 'GL', 'name' => 'Greenland', 'shipping_active' => false],
            ['code' => 'GD', 'name' => 'Grenada', 'shipping_active' => false],
            ['code' => 'GP', 'name' => 'Guadeloupe', 'shipping_active' => false],
            ['code' => 'GU', 'name' => 'Guam', 'shipping_active' => false],
            ['code' => 'GT', 'name' => 'Guatemala', 'shipping_active' => false],
            ['code' => 'GN', 'name' => 'Guinea', 'shipping_active' => false],
            ['code' => 'GW', 'name' => 'Guinea-Bissau', 'shipping_active' => false],
            ['code' => 'GY', 'name' => 'Guyana', 'shipping_active' => false],
            ['code' => 'HT', 'name' => 'Haiti', 'shipping_active' => false],
            ['code' => 'HM', 'name' => 'Heard and Mc Donald Islands', 'shipping_active' => false],
            ['code' => 'HN', 'name' => 'Honduras', 'shipping_active' => false],
            ['code' => 'HK', 'name' => 'Hong Kong', 'shipping_active' => false],
            ['code' => 'HU', 'name' => 'Hungary', 'shipping_active' => false],
            ['code' => 'IS', 'name' => 'Iceland', 'shipping_active' => false],
            ['code' => 'IN', 'name' => 'India', 'shipping_active' => true],
            ['code' => 'ID', 'name' => 'Indonesia', 'shipping_active' => true],
            ['code' => 'IR', 'name' => 'Iran (Islamic Republic of)', 'shipping_active' => false],
            ['code' => 'IQ', 'name' => 'Iraq', 'shipping_active' => false],
            ['code' => 'IE', 'name' => 'Ireland', 'shipping_active' => true],
            ['code' => 'IL', 'name' => 'Israel', 'shipping_active' => false],
            ['code' => 'IT', 'name' => 'Italy', 'shipping_active' => false],
            ['code' => 'CI', 'name' => 'Ivory Coast', 'shipping_active' => false],
            ['code' => 'JM', 'name' => 'Jamaica', 'shipping_active' => false],
            ['code' => 'JP', 'name' => 'Japan', 'shipping_active' => true],
            ['code' => 'JO', 'name' => 'Jordan', 'shipping_active' => false],
            ['code' => 'KZ', 'name' => 'Kazakhstan', 'shipping_active' => false],
            ['code' => 'KE', 'name' => 'Kenya', 'shipping_active' => false],
            ['code' => 'KI', 'name' => 'Kiribati', 'shipping_active' => false],
            ['code' => 'KP', 'name' => 'Korea, Democratic People\'s Republic of', 'shipping_active' => false],
            ['code' => 'KR', 'name' => 'Korea, Republic of', 'shipping_active' => false],
            ['code' => 'KW', 'name' => 'Kuwait', 'shipping_active' => false],
            ['code' => 'KG', 'name' => 'Kyrgyzstan', 'shipping_active' => false],
            ['code' => 'LA', 'name' => 'Lao People\'s Democratic Republic', 'shipping_active' => false],
            ['code' => 'LV', 'name' => 'Latvia', 'shipping_active' => true],
            ['code' => 'LB', 'name' => 'Lebanon', 'shipping_active' => false],
            ['code' => 'LS', 'name' => 'Lesotho', 'shipping_active' => false],
            ['code' => 'LR', 'name' => 'Liberia', 'shipping_active' => false],
            ['code' => 'LY', 'name' => 'Libyan Arab Jamahiriya', 'shipping_active' => false],
            ['code' => 'LI', 'name' => 'Liechtenstein', 'shipping_active' => false],
            ['code' => 'LT', 'name' => 'Lithuania', 'shipping_active' => false],
            ['code' => 'LU', 'name' => 'Luxembourg', 'shipping_active' => false],
            ['code' => 'MO', 'name' => 'Macau', 'shipping_active' => false],
            ['code' => 'MK', 'name' => 'Macedonia', 'shipping_active' => false],
            ['code' => 'MG', 'name' => 'Madagascar', 'shipping_active' => false],
            ['code' => 'MW', 'name' => 'Malawi', 'shipping_active' => false],
            ['code' => 'MY', 'name' => 'Malaysia', 'shipping_active' => true],
            ['code' => 'MV', 'name' => 'Maldives', 'shipping_active' => false],
            ['code' => 'ML', 'name' => 'Mali', 'shipping_active' => false],
            ['code' => 'MT', 'name' => 'Malta', 'shipping_active' => false],
            ['code' => 'MH', 'name' => 'Marshall Islands', 'shipping_active' => false],
            ['code' => 'MQ', 'name' => 'Martinique', 'shipping_active' => false],
            ['code' => 'MR', 'name' => 'Mauritania', 'shipping_active' => false],
            ['code' => 'MU', 'name' => 'Mauritius', 'shipping_active' => false],
            ['code' => 'TY', 'name' => 'Mayotte', 'shipping_active' => false],
            ['code' => 'MX', 'name' => 'Mexico', 'shipping_active' => false],
            ['code' => 'FM', 'name' => 'Micronesia, Federated States of', 'shipping_active' => false],
            ['code' => 'MD', 'name' => 'Moldova, Republic of', 'shipping_active' => false],
            ['code' => 'MC', 'name' => 'Monaco', 'shipping_active' => false],
            ['code' => 'MN', 'name' => 'Mongolia', 'shipping_active' => false],
            ['code' => 'MS', 'name' => 'Montserrat', 'shipping_active' => false],
            ['code' => 'MA', 'name' => 'Morocco', 'shipping_active' => false],
            ['code' => 'MZ', 'name' => 'Mozambique', 'shipping_active' => false],
            ['code' => 'MM', 'name' => 'Myanmar', 'shipping_active' => false],
            ['code' => 'NA', 'name' => 'Namibia', 'shipping_active' => false],
            ['code' => 'NR', 'name' => 'Nauru', 'shipping_active' => false],
            ['code' => 'NP', 'name' => 'Nepal', 'shipping_active' => false],
            ['code' => 'NL', 'name' => 'Netherlands', 'shipping_active' => false],
            ['code' => 'AN', 'name' => 'Netherlands Antilles', 'shipping_active' => false],
            ['code' => 'NC', 'name' => 'New Caledonia', 'shipping_active' => false],
            ['code' => 'NZ', 'name' => 'New Zealand', 'shipping_active' => false],
            ['code' => 'NI', 'name' => 'Nicaragua', 'shipping_active' => false],
            ['code' => 'NE', 'name' => 'Niger', 'shipping_active' => false],
            ['code' => 'NG', 'name' => 'Nigeria', 'shipping_active' => false],
            ['code' => 'NU', 'name' => 'Niue', 'shipping_active' => false],
            ['code' => 'NF', 'name' => 'Norfork Island', 'shipping_active' => false],
            ['code' => 'MP', 'name' => 'Northern Mariana Islands', 'shipping_active' => false],
            ['code' => 'NO', 'name' => 'Norway', 'shipping_active' => false],
            ['code' => 'OM', 'name' => 'Oman', 'shipping_active' => false],
            ['code' => 'PK', 'name' => 'Pakistan', 'shipping_active' => false],
            ['code' => 'PW', 'name' => 'Palau', 'shipping_active' => false],
            ['code' => 'PA', 'name' => 'Panama', 'shipping_active' => false],
            ['code' => 'PG', 'name' => 'Papua New Guinea', 'shipping_active' => false],
            ['code' => 'PY', 'name' => 'Paraguay', 'shipping_active' => false],
            ['code' => 'PE', 'name' => 'Peru', 'shipping_active' => false],
            ['code' => 'PH', 'name' => 'Philippines', 'shipping_active' => true],
            ['code' => 'PN', 'name' => 'Pitcairn', 'shipping_active' => false],
            ['code' => 'PL', 'name' => 'Poland', 'shipping_active' => false],
            ['code' => 'PT', 'name' => 'Portugal', 'shipping_active' => false],
            ['code' => 'PR', 'name' => 'Puerto Rico', 'shipping_active' => false],
            ['code' => 'QA', 'name' => 'Qatar', 'shipping_active' => false],
            ['code' => 'SS', 'name' => 'Republic of South Sudan', 'shipping_active' => false],
            ['code' => 'RE', 'name' => 'Reunion', 'shipping_active' => false],
            ['code' => 'RO', 'name' => 'Romania', 'shipping_active' => false],
            ['code' => 'RU', 'name' => 'Russian Federation', 'shipping_active' => false],
            ['code' => 'RW', 'name' => 'Rwanda', 'shipping_active' => false],
            ['code' => 'KN', 'name' => 'Saint Kitts and Nevis', 'shipping_active' => false],
            ['code' => 'LC', 'name' => 'Saint Lucia', 'shipping_active' => false],
            ['code' => 'VC', 'name' => 'Saint Vincent and the Grenadines', 'shipping_active' => false],
            ['code' => 'WS', 'name' => 'Samoa', 'shipping_active' => false],
            ['code' => 'SM', 'name' => 'San Marino', 'shipping_active' => false],
            ['code' => 'ST', 'name' => 'Sao Tome and Principe', 'shipping_active' => false],
            ['code' => 'SA', 'name' => 'Saudi Arabia', 'shipping_active' => false],
            ['code' => 'SN', 'name' => 'Senegal', 'shipping_active' => false],
            ['code' => 'RS', 'name' => 'Serbia', 'shipping_active' => false],
            ['code' => 'SC', 'name' => 'Seychelles', 'shipping_active' => false],
            ['code' => 'SL', 'name' => 'Sierra Leone', 'shipping_active' => false],
            ['code' => 'SG', 'name' => 'Singapore', 'shipping_active' => true],
            ['code' => 'SK', 'name' => 'Slovakia', 'shipping_active' => false],
            ['code' => 'SI', 'name' => 'Slovenia', 'shipping_active' => false],
            ['code' => 'SB', 'name' => 'Solomon Islands', 'shipping_active' => false],
            ['code' => 'SO', 'name' => 'Somalia', 'shipping_active' => false],
            ['code' => 'ZA', 'name' => 'South Africa', 'shipping_active' => false],
            ['code' => 'GS', 'name' => 'South Georgia South Sandwich Islands', 'shipping_active' => false],
            ['code' => 'ES', 'name' => 'Spain', 'shipping_active' => false],
            ['code' => 'LK', 'name' => 'Sri Lanka', 'shipping_active' => false],
            ['code' => 'SH', 'name' => 'St. Helena', 'shipping_active' => false],
            ['code' => 'PM', 'name' => 'St. Pierre and Miquelon', 'shipping_active' => false],
            ['code' => 'SD', 'name' => 'Sudan', 'shipping_active' => false],
            ['code' => 'SR', 'name' => 'Suriname', 'shipping_active' => false],
            ['code' => 'SJ', 'name' => 'Svalbarn and Jan Mayen Islands', 'shipping_active' => false],
            ['code' => 'SZ', 'name' => 'Swaziland', 'shipping_active' => false],
            ['code' => 'SE', 'name' => 'Sweden', 'shipping_active' => false],
            ['code' => 'CH', 'name' => 'Switzerland', 'shipping_active' => false],
            ['code' => 'SY', 'name' => 'Syrian Arab Republic', 'shipping_active' => false],
            ['code' => 'TW', 'name' => 'Taiwan', 'shipping_active' => false],
            ['code' => 'TJ', 'name' => 'Tajikistan', 'shipping_active' => false],
            ['code' => 'TZ', 'name' => 'Tanzania, United Republic of', 'shipping_active' => false],
            ['code' => 'TH', 'name' => 'Thailand', 'shipping_active' => false],
            ['code' => 'TG', 'name' => 'Togo', 'shipping_active' => false],
            ['code' => 'TK', 'name' => 'Tokelau', 'shipping_active' => false],
            ['code' => 'TO', 'name' => 'Tonga', 'shipping_active' => false],
            ['code' => 'TT', 'name' => 'Trinidad and Tobago', 'shipping_active' => false],
            ['code' => 'TN', 'name' => 'Tunisia', 'shipping_active' => false],
            ['code' => 'TR', 'name' => 'Turkey', 'shipping_active' => false],
            ['code' => 'TM', 'name' => 'Turkmenistan', 'shipping_active' => false],
            ['code' => 'TC', 'name' => 'Turks and Caicos Islands', 'shipping_active' => false],
            ['code' => 'TV', 'name' => 'Tuvalu', 'shipping_active' => false],
            ['code' => 'UG', 'name' => 'Uganda', 'shipping_active' => false],
            ['code' => 'UA', 'name' => 'Ukraine', 'shipping_active' => false],
            ['code' => 'AE', 'name' => 'United Arab Emirates', 'shipping_active' => false],
            ['code' => 'GB', 'name' => 'United Kingdom', 'shipping_active' => true],
            ['code' => 'UM', 'name' => 'United States minor outlying islands', 'shipping_active' => false],
            ['code' => 'UY', 'name' => 'Uruguay', 'shipping_active' => false],
            ['code' => 'UZ', 'name' => 'Uzbekistan', 'shipping_active' => false],
            ['code' => 'VU', 'name' => 'Vanuatu', 'shipping_active' => false],
            ['code' => 'VA', 'name' => 'Vatican City State', 'shipping_active' => false],
            ['code' => 'VE', 'name' => 'Venezuela', 'shipping_active' => false],
            ['code' => 'VN', 'name' => 'Vietnam', 'shipping_active' => false],
            ['code' => 'VG', 'name' => 'Virgin Islands (British)', 'shipping_active' => false],
            ['code' => 'VI', 'name' => 'Virgin Islands (U.S.)', 'shipping_active' => false],
            ['code' => 'WF', 'name' => 'Wallis and Futuna Islands', 'shipping_active' => false],
            ['code' => 'EH', 'name' => 'Western Sahara', 'shipping_active' => false],
            ['code' => 'YE', 'name' => 'Yemen', 'shipping_active' => false],
            ['code' => 'YU', 'name' => 'Yugoslavia', 'shipping_active' => false],
            ['code' => 'ZR', 'name' => 'Zaire', 'shipping_active' => false],
            ['code' => 'ZM', 'name' => 'Zambia', 'shipping_active' => false],
            ['code' => 'ZW', 'name' => 'Zimbabwe', 'shipping_active' => false],
        ];

        DB::table('countries')->insert($countries);
    }
}
